name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ 7.4, 8.0 ]
    steps:
      - uses: actions/checkout@master
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      
      - name: Composer install
        run: composer install --no-interaction --prefer-source --dev

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests/